import type { Component } from 'solid-js';
import {
  Bell,
  Camera,
  CircleDot,
  Droplets,
  Gauge,
  Lightbulb,
  Magnet,
  Mic,
  Move3D,
  Music,
  Power,
  Radio,
  RotateCw,
  SlidersHorizontal,
  Thermometer,
  Waves,
  Webcam,
  Wrench,
  Zap,
} from 'lucide-solid';

export type ModuleCategory = 'sensors' | 'actuators' | 'media';
export type ModuleCapability = 'gpio' | 'adc' | 'pwm' | 'i2c' | 'onewire' | 'multi' | 'usb' | 'none';
export type LocalizedText = { en: string; zh: string };

export type ModuleDefinition = {
  id: string;
  category: ModuleCategory;
  group: LocalizedText;
  name: LocalizedText;
  icon: Component<{ class?: string }>;
  capability: ModuleCapability;
  implemented: boolean;
  description: LocalizedText;
  wiring: LocalizedText;
  operation: LocalizedText;
  acceptance: LocalizedText[];
  controls?: Array<'read' | 'watch' | 'onoff' | 'level' | 'pwm' | 'color' | 'motion' | 'media'>;
};

const text = (zhText: string, enText: string): LocalizedText => ({ zh: zhText, en: enText });

export const MODULES: ModuleDefinition[] = [
  {
    id: 'sensor_gpio_light_break',
    category: 'sensors',
    group: text('GPIO', 'GPIO'),
    name: text('光遮断模块', 'GPIO Light Interrupter'),
    icon: Zap,
    capability: 'gpio',
    implemented: true,
    description: text('检测遮挡和无遮挡状态。', 'Detect blocked and clear states.'),
    wiring: text('选择一个 GPIO 接信号脚，模块 VCC/GND 接电源和地。', 'Connect signal to one GPIO, plus VCC and GND.'),
    operation: text('开始监听后，遮挡和无遮挡时观察数字电平变化。', 'After watching, compare the digital level when clear and blocked.'),
    acceptance: [text('无遮挡和遮挡两种状态的数字电平应不同。', 'Clear and blocked states should read different digital levels.')],
    controls: ['read', 'watch'],
  },
  {
    id: 'sensor_gpio_mercury_tilt',
    category: 'sensors',
    group: text('GPIO', 'GPIO'),
    name: text('水银倾斜开关', 'GPIO Mercury Tilt Switch'),
    icon: SlidersHorizontal,
    capability: 'gpio',
    implemented: true,
    description: text('检测倾斜方向导致的导通/断开。', 'Detect tilt-triggered open or closed state.'),
    wiring: text('信号脚接 GPIO，VCC/GND 接电源和地。', 'Connect signal to GPIO, plus VCC and GND.'),
    operation: text('打开开关和关闭开关时，分别观察数字电平。', 'Open and close the switch, then compare the digital level.'),
    acceptance: [text('打开开关是一种电平，关闭开关是另外一种电平。', 'Open and closed switch states should read different digital levels.')],
    controls: ['read', 'watch'],
  },
  {
    id: 'sensor_gpio_button',
    category: 'sensors',
    group: text('GPIO', 'GPIO'),
    name: text('按键模块', 'GPIO Button'),
    icon: CircleDot,
    capability: 'gpio',
    implemented: true,
    description: text('读取按键模块输出的数字电平。', 'Read the button module digital level.'),
    wiring: text('信号脚接 GPIO，按键模块接 VCC/GND。', 'Connect signal to GPIO, plus VCC and GND.'),
    operation: text('按下和松开按键时，分别观察数字电平。', 'Press and release the button, then compare the digital level.'),
    acceptance: [text('按下和松开两种状态的数字电平应不同。', 'Pressed and released states should read different digital levels.')],
    controls: ['read', 'watch'],
  },
  {
    id: 'sensor_gpio_reed_switch',
    category: 'sensors',
    group: text('GPIO', 'GPIO'),
    name: text('磁簧开关', 'GPIO Reed Switch'),
    icon: Magnet,
    capability: 'gpio',
    implemented: true,
    description: text('检测磁铁靠近或远离。', 'Detect a magnet approaching or leaving.'),
    wiring: text('信号脚接 GPIO，模块接 VCC/GND。', 'Connect signal to GPIO, plus VCC and GND.'),
    operation: text('磁铁靠近和远离时，分别观察数字电平。', 'Move the magnet near and far, then compare the digital level.'),
    acceptance: [text('靠近和远离两种状态的数字电平应不同。', 'Near and far states should read different digital levels.')],
    controls: ['read', 'watch'],
  },
  {
    id: 'sensor_gpio_ir_tracking',
    category: 'sensors',
    group: text('GPIO', 'GPIO'),
    name: text('红外循迹模块 TCRT5000', 'TCRT5000 IR Tracking Sensor'),
    icon: Radio,
    capability: 'gpio',
    implemented: true,
    description: text('检测黑线或反射差异。', 'Detect black line or reflection changes.'),
    wiring: text('数字输出接 GPIO，VCC/GND 接电源和地。', 'Connect digital output to GPIO, plus VCC and GND.'),
    operation: text('白底和黑线下分别观察数字电平。', 'Compare the digital level on white background and black line.'),
    acceptance: [text('白底和黑线两种状态的数字电平应不同。', 'White background and black line should read different digital levels.')],
    controls: ['read', 'watch'],
  },
  {
    id: 'sensor_gpio_active_buzzer',
    category: 'sensors',
    group: text('GPIO', 'GPIO'),
    name: text('有源蜂鸣器', 'Active Buzzer'),
    icon: Bell,
    capability: 'gpio',
    implemented: true,
    description: text('GPIO 高低电平控制蜂鸣器开关。', 'Switch an active buzzer with GPIO level.'),
    wiring: text('信号脚接 GPIO，蜂鸣器接电源和地。', 'Connect signal to GPIO, plus power and GND.'),
    operation: text('点击打开/关闭测试蜂鸣器。', 'Use on/off controls to test the buzzer.'),
    acceptance: [text('打开时蜂鸣，关闭时停止。', 'It sounds when on and stops when off.')],
    controls: ['onoff'],
  },
  {
    id: 'sensor_gpio_dual_led',
    category: 'sensors',
    group: text('GPIO', 'GPIO'),
    name: text('双色 LED', 'Dual Color LED'),
    icon: Lightbulb,
    capability: 'gpio',
    implemented: true,
    description: text('一个 GPIO 输出高/低电平，对应两种颜色。', 'One GPIO output level selects one of two colors.'),
    wiring: text('信号脚接 GPIO，模块 VCC/GND 接电源和地。', 'Connect signal to GPIO, plus VCC and GND.'),
    operation: text('点击高电平/低电平，观察模块颜色变化。', 'Click high/low output and watch the color change.'),
    acceptance: [text('输出高电平是一种颜色，输出低电平是另外一种颜色。', 'High output shows one color and low output shows the other color.')],
    controls: ['level'],
  },
  {
    id: 'sensor_gpio_traffic_led',
    category: 'sensors',
    group: text('GPIO', 'GPIO'),
    name: text('三色灯模块', 'Traffic Light LED'),
    icon: Lightbulb,
    capability: 'multi',
    implemented: true,
    description: text('三个 GPIO 分别控制红、蓝、绿三路，共 GND。', 'Three GPIO outputs control red, blue, and green channels with common GND.'),
    wiring: text('模块 GND 接地，红/蓝/绿三个信号脚分别接三个 GPIO。', 'Connect module GND to ground, and red/blue/green signal pins to three GPIOs.'),
    operation: text('点击红灯、蓝灯、绿灯或全部关闭，观察对应灯是否点亮。', 'Click red, blue, green, or all off and watch the matching LED.'),
    acceptance: [text('点击红灯、蓝灯、绿灯时，应分别只有对应颜色点亮；点击全部关闭后应全部熄灭。', 'Red, blue, and green buttons should light only the matching color; all off should turn everything off.')],
    controls: ['color'],
  },
  {
    id: 'sensor_adc_photoresistor',
    category: 'sensors',
    group: text('ADC', 'ADC'),
    name: text('光敏电阻模块', 'ADC Photoresistor Sensor'),
    icon: Lightbulb,
    capability: 'adc',
    implemented: true,
    description: text('读取光照变化对应的 ADC 数值。', 'Read ADC value for light changes.'),
    wiring: text('模拟输出 AO 接 ADC 引脚。', 'Connect analog output AO to an ADC pin.'),
    operation: text('遮挡或照亮模块，观察数值变化。', 'Cover or illuminate the sensor and watch value changes.'),
    acceptance: [text('亮度越高，数值越小。', 'Higher brightness gives a smaller value.')],
    controls: ['read', 'watch'],
  },
  {
    id: 'sensor_adc_water_level',
    category: 'sensors',
    group: text('ADC', 'ADC'),
    name: text('水位检测模块', 'ADC Water Level Sensor'),
    icon: Droplets,
    capability: 'adc',
    implemented: true,
    description: text('读取水位变化对应的 ADC 数值。', 'Read ADC value for water level changes.'),
    wiring: text('模拟输出接 ADC 引脚，注意防水和供电安全。', 'Connect analog output to ADC and keep wiring safe around water.'),
    operation: text('水位升高时观察数值变化。', 'Raise water level and watch value changes.'),
    acceptance: [text('水越多，数值越高。', 'More water gives a larger value.')],
    controls: ['read', 'watch'],
  },
  {
    id: 'sensor_joystick',
    category: 'sensors',
    group: text('GPIO & ADC', 'GPIO & ADC'),
    name: text('双轴摇杆模块', 'Analog Joystick'),
    icon: Move3D,
    capability: 'multi',
    implemented: true,
    description: text('读取 X/Y 两路 ADC 和按键 GPIO。', 'Read X/Y ADC values plus button GPIO.'),
    wiring: text('VRx/VRy 接两个 ADC，引脚 SW 接 GPIO。', 'Connect VRx/VRy to two ADC pins and SW to GPIO.'),
    operation: text('推动摇杆观察 X/Y 模拟电压；按下和松开按键时观察数字电平。', 'Move the joystick to watch X/Y analog voltage; press and release the button to compare digital level.'),
    acceptance: [text('左右上下推动时 X/Y 数值连续变化。', 'X/Y values change continuously while moving.'), text('按键按下和松开两种状态的数字电平应不同。', 'Button pressed and released states should read different digital levels.')],
    controls: ['read', 'watch'],
  },
  {
    id: 'sensor_soil_moisture',
    category: 'sensors',
    group: text('GPIO & ADC', 'GPIO & ADC'),
    name: text('土壤湿度模块', 'Soil Moisture Sensor'),
    icon: Droplets,
    capability: 'multi',
    implemented: true,
    description: text('同时读取 AO 模拟湿度和 DO 比较器电平。', 'Read AO analog moisture and DO comparator level together.'),
    wiring: text('AO 接 ADC 引脚，DO 接 GPIO，引脚 GND/VCC 接电源。', 'Connect AO to ADC, DO to GPIO, plus GND/VCC power.'),
    operation: text('插入干燥和潮湿土壤，观察模拟电压和数字电平变化。', 'Test dry and wet soil, then watch analog voltage and digital level changes.'),
    acceptance: [text('干湿状态切换时，AO 数值应变化，DO 数字电平也应出现一种高低变化。', 'When dry/wet state changes, AO should move and DO should show one of two digital levels.')],
    controls: ['read', 'watch'],
  },
  {
    id: 'sensor_sound_level',
    category: 'sensors',
    group: text('GPIO & ADC', 'GPIO & ADC'),
    name: text('声音强度模块', 'Sound Level Sensor'),
    icon: Mic,
    capability: 'multi',
    implemented: true,
    description: text('同时读取 AO 声音幅度和 DO 比较器电平。', 'Read AO sound amplitude and DO comparator level together.'),
    wiring: text('AO 接 ADC 引脚，DO 接 GPIO，引脚 GND/VCC 接电源。', 'Connect AO to ADC, DO to GPIO, plus GND/VCC power.'),
    operation: text('说话或拍手，观察模拟电压和数字电平变化。', 'Speak or clap and watch analog voltage and digital level changes.'),
    acceptance: [text('声音变化时 AO 数值应波动；超过模块电位器阈值时，DO 电平应切换。', 'AO should fluctuate with sound; DO should switch when sound crosses the module threshold.')],
    controls: ['read', 'watch'],
  },
  {
    id: 'sensor_pwm_passive_buzzer',
    category: 'sensors',
    group: text('PWM', 'PWM'),
    name: text('无源蜂鸣器', 'Passive Buzzer'),
    icon: Music,
    capability: 'pwm',
    implemented: true,
    description: text('用 PWM 频率驱动无源蜂鸣器发声。', 'Drive a passive buzzer with PWM frequency.'),
    wiring: text('信号脚接支持 PWM 的 GPIO。', 'Connect signal to a PWM-capable GPIO.'),
    operation: text('选择一首旋律后点击播放，停止按钮会关闭 PWM 输出。', 'Choose a melody and play it; Stop turns off PWM output.'),
    acceptance: [text('两只老虎、一闪一闪亮晶晶、如愿简版三种旋律可分别听到。', 'Two Tigers, Twinkle, and Ru Yuan short pattern can each be heard.')],
    controls: ['pwm'],
  },
  {
    id: 'sensor_onewire_ds18b20',
    category: 'sensors',
    group: text('单总线', 'One-Wire'),
    name: text('DS18B20 温度传感器', 'DS18B20 Temperature Sensor'),
    icon: Thermometer,
    capability: 'onewire',
    implemented: true,
    description: text('实时读取 DS18B20 温度。', 'Read DS18B20 temperature live.'),
    wiring: text('DQ 接数据 GPIO，建议加 4.7k 上拉。', 'Connect DQ to data GPIO and use a 4.7k pull-up.'),
    operation: text('选择 DQ 引脚后自动实时显示温度。', 'After selecting DQ, temperature is shown live.'),
    acceptance: [text('页面实时显示温度数值，手握探头时温度应变化。', 'The page shows live temperature, and the value changes when holding the probe.')],
    controls: ['read', 'watch'],
  },
  {
    id: 'sensor_onewire_dht11',
    category: 'sensors',
    group: text('单总线', 'One-Wire'),
    name: text('DHT11 温湿度传感器', 'DHT11 Temperature Humidity'),
    icon: Thermometer,
    capability: 'onewire',
    implemented: true,
    description: text('读取温度和湿度。', 'Read temperature and humidity.'),
    wiring: text('DATA 接数据 GPIO，VCC/GND 接电源和地。', 'Connect DATA to data GPIO, plus VCC and GND.'),
    operation: text('选择 DATA 引脚后自动实时显示温度和湿度。', 'After selecting DATA, temperature and humidity are shown live.'),
    acceptance: [text('页面实时显示温度和湿度数值。', 'The page shows live temperature and humidity values.')],
    controls: ['read', 'watch'],
  },
  {
    id: 'sensor_onewire_rgb_led',
    category: 'sensors',
    group: text('单总线', 'One-Wire'),
    name: text('全彩 RGB 模块', 'RGB LED Module'),
    icon: Lightbulb,
    capability: 'onewire',
    implemented: true,
    description: text('单颗 WS2812/全彩 RGB 模块颜色控制。', 'Control a single WS2812/full-color RGB module.'),
    wiring: text('DIN 接数据 GPIO，VCC/GND 接电源并与开发板共地。', 'Connect DIN to data GPIO, power VCC/GND, and share ground with the board.'),
    operation: text('点击红灯、蓝灯、绿灯或全部关闭，观察灯珠颜色。', 'Click red, blue, green, or all off and watch the LED color.'),
    acceptance: [text('红、蓝、绿和关闭状态都能正确切换。', 'Red, blue, green, and off states switch correctly.')],
    controls: ['color'],
  },
  {
    id: 'sensor_onewire_ws2812_ring',
    category: 'sensors',
    group: text('单总线', 'One-Wire'),
    name: text('WS2812 灯环', 'WS2812 LED Ring'),
    icon: Lightbulb,
    capability: 'onewire',
    implemented: true,
    description: text('单数据线控制 WS2812 灯环。', 'Control WS2812 ring with one data line.'),
    wiring: text('DIN 接数据 GPIO，注意 5V/GND 共地。', 'Connect DIN to data GPIO; share GND with 5V power.'),
    operation: text('选择颜色、亮度和灯珠数量后测试。', 'Choose color, brightness, and LED count for testing.'),
    acceptance: [text('红绿蓝白和流水灯测试正常。', 'Red, green, blue, white, and chase tests work.')],
    controls: ['color'],
  },
  {
    id: 'sensor_i2c_mpu6050',
    category: 'sensors',
    group: text('I2C', 'I2C'),
    name: text('MPU6050 姿态传感器', 'MPU6050 IMU'),
    icon: Gauge,
    capability: 'i2c',
    implemented: true,
    description: text('读取加速度和角速度。', 'Read acceleration and gyroscope data.'),
    wiring: text('选择 SDA/SCL，模块地址通常为 0x68。', 'Select SDA/SCL; typical address is 0x68.'),
    operation: text('移动模块，观察数值变化。', 'Move the module and watch values change.'),
    acceptance: [text('静止和晃动时数值不同。', 'Still and moving states read differently.')],
    controls: ['read', 'watch'],
  },
  {
    id: 'sensor_rotary_encoder',
    category: 'sensors',
    group: text('其它', 'Other'),
    name: text('旋转编码器', 'Rotary Encoder'),
    icon: RotateCw,
    capability: 'multi',
    implemented: true,
    description: text('读取旋转方向和计数。', 'Read rotation direction and count.'),
    wiring: text('CLK/DT 接两个 GPIO，SW 可选接一个 GPIO。', 'Connect CLK/DT to two GPIOs and optional SW to one GPIO.'),
    operation: text('旋转编码器，观察计数增减。', 'Rotate and watch count increase or decrease.'),
    acceptance: [text('顺逆时针计数方向相反。', 'Clockwise and counter-clockwise count in opposite directions.')],
    controls: ['read', 'watch'],
  },
  {
    id: 'sensor_hcsr04_ultrasonic',
    category: 'sensors',
    group: text('其它', 'Other'),
    name: text('HC-SR04 超声波测距模块', 'HC-SR04 Ultrasonic Sensor'),
    icon: Waves,
    capability: 'multi',
    implemented: true,
    description: text('用 Trig/Echo 测量距离。', 'Measure distance with Trig and Echo pins.'),
    wiring: text('Trig 和 Echo 分别接两个 GPIO，注意 Echo 电平匹配。', 'Connect Trig and Echo to two GPIOs; level-shift Echo if needed.'),
    operation: text('选择 Trig/Echo 后自动实时显示厘米距离。', 'After selecting Trig/Echo, distance is shown live in centimeters.'),
    acceptance: [text('移动障碍物远近时，厘米距离应跟随变化。', 'Moving an obstacle closer or farther changes the centimeter reading.')],
    controls: ['read', 'watch'],
  },
  {
    id: 'actuator_pwm_servo',
    category: 'actuators',
    group: text('舵机', 'Servo'),
    name: text('PWM 舵机', 'PWM Servo'),
    icon: Wrench,
    capability: 'pwm',
    implemented: true,
    description: text('通过 PWM 控制舵机角度。', 'Control servo angle with PWM.'),
    wiring: text('信号线接 PWM GPIO，舵机单独供电并共地。', 'Connect signal to PWM GPIO; power servo separately with common GND.'),
    operation: text('选择角度后点击应用。', 'Choose an angle and apply.'),
    acceptance: [text('0/90/180 度动作正常。', '0/90/180 degree positions work.')],
    controls: ['motion'],
  },
  {
    id: 'actuator_multi_servo',
    category: 'actuators',
    group: text('舵机', 'Servo'),
    name: text('多路舵机测试', 'Multi Servo Tester'),
    icon: Wrench,
    capability: 'multi',
    implemented: true,
    description: text('测试最多四路舵机。', 'Test up to four servo channels.'),
    wiring: text('为每路舵机选择一个 PWM GPIO。', 'Select one PWM GPIO per servo channel.'),
    operation: text('逐路选择角度并测试。', 'Set and test angle per channel.'),
    acceptance: [text('每路舵机能独立动作。', 'Each servo moves independently.')],
    controls: ['motion'],
  },
  {
    id: 'actuator_stepper_28byj48',
    category: 'actuators',
    group: text('电机', 'Motor'),
    name: text('28BYJ-48 步进电机', '28BYJ-48 Stepper Motor'),
    icon: RotateCw,
    capability: 'multi',
    implemented: true,
    description: text('四相步进电机控制。', 'Control a four-phase stepper motor.'),
    wiring: text('IN1-IN4 分别接四个 GPIO，使用 ULN2003 驱动板。', 'Connect IN1-IN4 to four GPIOs using a ULN2003 driver board.'),
    operation: text('设置步数、转速和方向后运行。', 'Set steps, RPM, and direction before running.'),
    acceptance: [text('正反转都能按步数动作。', 'Forward and reverse moves match requested steps.')],
    controls: ['motion'],
  },
  {
    id: 'actuator_dc_motor',
    category: 'actuators',
    group: text('电机', 'Motor'),
    name: text('直流电机驱动', 'DC Motor Driver'),
    icon: Power,
    capability: 'pwm',
    implemented: false,
    description: text('直流电机驱动页面预留。', 'Reserved page for DC motor drivers.'),
    wiring: text('后续按驱动板选择 IN/PWM 引脚。', 'Future version will select IN/PWM pins per driver board.'),
    operation: text('当前版本暂未实现。', 'Not implemented in this version.'),
    acceptance: [text('后续应支持方向和速度控制。', 'Future version should support direction and speed control.')],
  },
  {
    id: 'actuator_motor_expansion',
    category: 'actuators',
    group: text('电机', 'Motor'),
    name: text('电机驱动扩展预留', 'Motor Driver Expansion'),
    icon: Power,
    capability: 'none',
    implemented: false,
    description: text('预留给后续电机驱动板。', 'Reserved for future motor driver boards.'),
    wiring: text('当前版本无接线要求。', 'No wiring required in this version.'),
    operation: text('当前版本只显示说明。', 'This version only shows instructions.'),
    acceptance: [text('页面显示预留状态。', 'The page shows reserved status.')],
  },
  {
    id: 'media_usb_microphone',
    category: 'media',
    group: text('音频输入', 'Audio Input'),
    name: text('USB 麦克风', 'USB Microphone'),
    icon: Mic,
    capability: 'usb',
    implemented: false,
    description: text('USB UAC 麦克风输入测试。', 'USB UAC microphone input test.'),
    wiring: text('插入 USB 音频设备。', 'Connect a USB audio device.'),
    operation: text('后续显示麦克风电平。', 'Future version will show microphone level.'),
    acceptance: [text('页面显示预留状态。', 'The page shows reserved status.')],
    controls: ['media'],
  },
  {
    id: 'media_usb_speaker',
    category: 'media',
    group: text('音频输出', 'Audio Output'),
    name: text('USB 喇叭', 'USB Speaker'),
    icon: Music,
    capability: 'usb',
    implemented: false,
    description: text('USB UAC 喇叭输出测试。', 'USB UAC speaker output test.'),
    wiring: text('插入 USB 音频设备。', 'Connect a USB audio device.'),
    operation: text('后续播放测试音。', 'Future version will play a test tone.'),
    acceptance: [text('页面显示预留状态。', 'The page shows reserved status.')],
    controls: ['media'],
  },
  {
    id: 'media_usb_uvc_camera',
    category: 'media',
    group: text('视频输入', 'Video Input'),
    name: text('USB UVC 摄像头', 'USB UVC Camera'),
    icon: Webcam,
    capability: 'usb',
    implemented: false,
    description: text('USB UVC 摄像头预览和拍照。', 'USB UVC camera preview and snapshot.'),
    wiring: text('插入 USB 摄像头。', 'Connect a USB camera.'),
    operation: text('后续启用预览和拍照。', 'Future version will enable preview and snapshot.'),
    acceptance: [text('页面显示预留状态。', 'The page shows reserved status.')],
    controls: ['media'],
  },
  {
    id: 'media_dvp_camera',
    category: 'media',
    group: text('视频输入', 'Video Input'),
    name: text('DVP 摄像头', 'DVP Camera'),
    icon: Camera,
    capability: 'none',
    implemented: false,
    description: text('DVP 摄像头功能预留。', 'Reserved page for DVP camera support.'),
    wiring: text('后续支持 OV2640 / OV3660 等并口摄像头模块。', 'Future support for OV2640 / OV3660 style parallel cameras.'),
    operation: text('当前版本暂未启用，请使用 USB UVC 摄像头。', 'Not enabled in this version; use USB UVC camera instead.'),
    acceptance: [text('页面显示预留状态。', 'The page shows reserved status.')],
  },
  {
    id: 'media_usb_composite_camera',
    category: 'media',
    group: text('复合设备', 'Composite Device'),
    name: text('USB 三合一摄像头', 'USB Composite Camera'),
    icon: Webcam,
    capability: 'usb',
    implemented: false,
    description: text('包含 UVC 摄像头、UAC 麦克风和 UAC 喇叭。', 'Includes UVC camera, UAC microphone, and UAC speaker.'),
    wiring: text('插入 USB 三合一复合设备。', 'Connect the USB composite camera device.'),
    operation: text('页面拆分设备状态、音频测试和视频测试。', 'The page separates device status, audio tests, and video tests.'),
    acceptance: [
      text('能显示 UVC/UAC 状态。', 'Shows UVC/UAC status.'),
      text('后续支持麦克风、喇叭和视频测试。', 'Future version supports microphone, speaker, and video tests.'),
    ],
    controls: ['media'],
  },
];

export function modulesForCategory(category: ModuleCategory) {
  return MODULES.filter((item) => item.category === category);
}
